### ISSUE TITLE
 I could not find any billing report under Bucket 

### ISSUE THREAD

**Issue by pankaj-kakade** [PriceBoardIn/aws-elk-billing#10]
I have installed the docker and I am getting the error . I am using Linked AWS accounts , dont have permissions to configure the reports on AWS console . 

Our payer provide us .CSV files can you suggest how to pull those files for reporting.

Regards
Pankaj

**Comment by droidlabour** [comment]
This space is only used to keep track of issues. The idea of the overall project is to make the installation and configuration as seamless as possible. What you're asking can be done although it'll be quite hacky.
