### ISSUE TITLE
ERROR: Error: image priceboard/elasticsearch:2.3.3 not found

### ISSUE THREAD

**Issue by muke5hy** [PriceBoardIn/aws-elk-billing#11]
Getting error while doing `docker-compose up`

**Comment by droidlabour** [comment]
@muke5hy Sorry I forgot to merge `upadte_stack` to `master`
It should be fine now. https://github.com/PriceBoardIn/aws-elk-billing/commit/01725313e60c0fd63e74e7565753a398a92e7471
