### ISSUE TITLE
I could not find any billing report under Bucket  under Path 

### ISSUE THREAD

**Issue by prasenforu** [PriceBoardIn/aws-elk-billing#12]
I could not find any billing report under <bucketname>  under Path <path name>

getting all time same error, did multiple combination in prod.env file but same error.

Thnx :)

Prasen

**Comment by droidlabour** [comment]
@prasenforu `S3_REPORT_PATH` must have the value exactly as mentioned by `Report path` field at [ billing reports page](https://console.aws.amazon.com/billing/home?region=ap-southeast-1#/reports)

**Comment by prasenforu** [comment]
Thanks man for reply.

When I did "creating report" at billing reports page as follows

![image](https://cloud.githubusercontent.com/assets/19322497/21961518/8c0b2bfc-db31-11e6-9aea-6dc4d6e3d80c.png)


 then after 24 later I got file in


![image](https://cloud.githubusercontent.com/assets/19322497/21961511/54f16f28-db31-11e6-9a11-be05d4b6d227.png)

I did all, 

Please suggest me what show my prod.env file as per above picture.

Thanks :)

**Comment by droidlabour** [comment]
Can you post a screenshot of your billing reports page. It must look something [like this.](https://raw.githubusercontent.com/PriceBoardIn/aws-elk-billing/master/screenshots/aws%20cost%20and%20usage%20reports%20console.png)

**Comment by prasenforu** [comment]
Now a day its not visible. This changes I noticed in January 17 onwards. 
That is why I took initial screen shot.

You can try, the screen shot you send its old. 

So once you create request after that not visible that record but you will get report data.

**Comment by droidlabour** [comment]
oh I see. Thanks for the info. In that case the value for `S3_REPORT_PATH ` will be `/awscoebilling`

**Comment by prasenforu** [comment]
OK will try one more time and let you know. 

For this setup its not working t2.micro due to memory issue. 

So for that I have to choose t2.medium which is changeable and not in free tier.

Any way I dowloaded the bill csv file kept in test/sample folder then rename that file  with "test_ub_cost_2016-06.csv" then run "docker-compose -f docker-compose-test.yml up -d"

Then followed below steps 

![image](https://cloud.githubusercontent.com/assets/19322497/21961665/d8f6c404-db35-11e6-901f-c3aee25e9569.png)

But Dashboard not coming.

Anyway .... 

Thanks your reply.. 

will update you :)

**Comment by prasenforu** [comment]
One more thing I forgot to tell you that recently when AWS sending report your bucket its create and empty folder as below.

![image](https://cloud.githubusercontent.com/assets/19322497/21961690/fc0ede9e-db36-11e6-935e-c811f546839e.png)

just FYI

**Comment by droidlabour** [comment]
Yeah that's fine. Because`S3_REPORT_PATH` starts with `/`

**Comment by prasenforu** [comment]
and report name file 
S3_REPORT_NAME=awscoebilling-1.cvs.gz

or only 

S3_REPORT_NAME=awscoebilling

Let me know do I need to give "/" before file name

S3_REPORT_NAME=/awscoebilling

**Comment by droidlabour** [comment]
It will be `S3_REPORT_NAME=awscoebilling`

**Comment by prasenforu** [comment]
so prod.env file should be as follows..

AWS_ACCESS_KEY_ID=YOUR_ACCESS_ID
AWS_SECRET_ACCESS_KEY=YOUR_SECRET_KEY
S3_BUCKET_NAME=billing-aws-adb-pkar
S3_REPORT_PATH=/awscoebilling
S3_REPORT_NAME=/awscoebilling

S3_BUCKET_NAME=billing-aws-adb-pkar   is that correct ? or any "/" before that also

**Comment by droidlabour** [comment]
Sorry I updated my previous comment. Just change `S3_REPORT_NAME=awscoebilling`
Everything else looks good.

**Comment by prasenforu** [comment]
Ok Let me try NOW :) 

Please pray good luck for me :) 

yday onward I launched 10 times t2.medium ;)

**Comment by prasenforu** [comment]
Fantastic :) 

Thanks you man it worked .......

**Comment by droidlabour** [comment]
@prasenforu Glad I could help. Would love to hear your feedback.
Thanks

**Comment by prasenforu** [comment]
I am not sure how to send feedback, please guide me.

I am happy to send feedback.

By the way if my entire environment (all container) running, will this pull biiling report from S3 everyday ?

**Comment by droidlabour** [comment]
@prasenforu In order to pull new billing report you need to restart the container.
`docker-compose restart` will be good enough.
Email Sent. :)
