### ISSUE TITLE
Can't get reports

### ISSUE THREAD

**Issue by epik0r** [PriceBoardIn/aws-elk-billing#13]
`root@3ad7de2f0850:/aws-elk-billing# python orchestrate.py
Checking if Elasticsearch container has started to listen to 9200
Great Elasticsearch is listening on 9200, 9300 :)
Checking if Logstash container has started to listen to 5140
Great Logstash is listening on 5140 :)
Checking if Kibana container has started to listen to 5160
Great Kibana is listening on 5601 :)
Template already exists
Traceback (most recent call last):
  File "orchestrate.py", line 27, in <module>
    s3_dir_to_index = tools.get_s3_bucket_dir_to_index()
  File "/aws-elk-billing/tools/tools.py", line 101, in get_s3_bucket_dir_to_index
    Prefix=Key,
NameError: global name 'Key' is not defined`

My "Prefix" seems to be empty and there are not "CommonKeys" in the output. 
` u'Prefix': '', u'Marker': u'', u'EncodingType': 'url', u'IsTruncated': False,`

**Comment by droidlabour** [comment]
@bc-bjoern Looks like your`S3_REPORT_PATH` is not set correctly.
Can you post a screenshot of your `AWS Cost and Usage Report` settings.
