### ISSUE TITLE
issue with docker pull 

### ISSUE THREAD

**Issue by Nanyte25** [PriceBoardIn/aws-elk-billing#25]
I am having permissions issue docker pull priceboard/elasticsearch.

 sudo docker-compose up
Pulling elasticsearch (priceboard/elasticsearch:2.3.3)...
ERROR: pull access denied for priceboard/elasticsearch, repository does not exist or may require 'docker login'

**Comment by Nanyte25** [comment]
already performed docker login

**Comment by droidlabour** [comment]
@Nanyte25 Looks like you're using older revision.
Please update your HEAD with the latest `master` rev.
