### ISSUE TITLE
RE: Pulling results for detailed billing

### ISSUE THREAD

**Issue by newlyregistered26** [PriceBoardIn/aws-elk-billing#5]
Hi there,
I really like what this project says on the tin and would like to use it for reserved billing.

I've confirmed access to my S3 bucket, 
from prod.env
S3_BUCKET_NAME=somebucket
S3_BILL_PATH_NAME=/yyyymmdd-yyyymmdd/detailed/date-range

Here is the actual S3 url
https://s3-ap-southeast-2.amazonaws.com/somebucket/yyyymmdd-yyyymmdd/detailed/20160601-20160701/b5791861-df60-4521-bccf-1eb414fd8da9/detailed-1.csv.gz

I've tried removing the leading slash as someone else suggested, is there anything simple that I am missing here, I'm a total noob to python, so can't understand the syntax, Am hoping it's a fairly simple fix, 

Here is the exception thrown,
Traceback (most recent call last):
  File "/aws-elk-billing/orchestrate.py", line 27, in <module>
    s3_dir_to_index = tools.get_s3_bucket_dir_to_index()
  File "/aws-elk-billing/tools/tools.py", line 100, in get_s3_bucket_dir_to_index
    for keys in key_names['CommonPrefixes']:
KeyError: 'CommonPrefixes'

Thanks in advance,

Andrew

**Comment by droidlabour** [comment]
Currently this project supports `AWS Cost and Usage Report` 
Here's how you can activate it.
http://docs.aws.amazon.com/awsaccountbilling/latest/aboutv2/detailed-billing-reports.html#turnonreports

Besides the `prod.env` file must have the values as mentioned in the README below.
https://github.com/PriceBoardIn/aws-elk-billing/blob/master/README.md#set-s3-credentials-and-aws-billing-bucket-and-directory-name
